_wandb:
    value:
        cli_version: 0.18.5
        m: []
        mask/class_labels:
            Validation Example_wandb_delimeter_ground_truth:
                key: Validation Example_wandb_delimeter_ground_truth
                type: mask/class_labels
                value:
                    "0": no building
                    "1": building
            Validation Example_wandb_delimeter_predictions:
                key: Validation Example_wandb_delimeter_predictions
                type: mask/class_labels
                value:
                    "0": no building
                    "1": building
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
settings:
    value:
        projectPrivacy: public
