_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.14
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
