_wandb:
    value:
        cli_version: 0.18.5
        m: []
        mask/class_labels:
            Validation Example_wandb_delimeter_ground_truth:
                key: Validation Example_wandb_delimeter_ground_truth
                type: mask/class_labels
                value:
                    "0": no building
                    "1": building
            Validation Example_wandb_delimeter_predictions:
                key: Validation Example_wandb_delimeter_predictions
                type: mask/class_labels
                value:
                    "0": no building
                    "1": building
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
Normalize:
    value:
        DataCentric:
            mean:
                - 72.74413315
                - 99.76137101
                - 82.70024275
            std:
                - 36.28290664
                - 34.82507359
                - 41.48902725
        WHU:
            mean:
                - 105.34253814
                - 114.2284708
                - 112.52936415
            std:
                - 42.12451161
                - 39.52149692
                - 42.81161886
        apply: true
data:
    value:
        batch_size: 16
        datacentric_image_path: /media/tidop/Datos_4TB/databases/kaggle/dataset/training_patches
        label_noisy_path: /media/tidop/Datos_4TB/databases/kaggle/dataset/training_noisy_labels
        num_workers: 16
        whu_path: /media/tidop/Datos_4TB/databases/whu
device:
    value: cuda
knowledge_distillation:
    value:
        alpha: 0.7
        beta: 0.3
learning_rate:
    value: "1e-4"
trainer:
    value:
        experiment_name: Student Training
        max_epochs: 20
        wandb_project: UNet-Attention-Teacher-Student-Training
