_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": image.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": image.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_precision
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_f1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_precision
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.predictions.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.predictions.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.ground_truth.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.ground_truth._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_iou
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_recall
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.ground_truth.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_iou
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_recall
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.predictions.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_f1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.predictions._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": image.masks.ground_truth.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        mask/class_labels:
            image_wandb_delimeter_ground_truth:
                key: image_wandb_delimeter_ground_truth
                type: mask/class_labels
                value:
                    "0": background
                    "1": building
            image_wandb_delimeter_predictions:
                key: image_wandb_delimeter_predictions
                type: mask/class_labels
                value:
                    "0": background
                    "1": building
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.14
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
